namespace COMP003A.Assignment1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("100 Things About Me!");
            Console.Write("Press Enter to Start");
            Console.ReadLine();
            Console.WriteLine("1. My name is Isaac");
            Console.WriteLine("2. I like going to the gym");
            Console.WriteLine("3. I work at amazon");
            Console.WriteLine("4. I run my department at work");
            Console.WriteLine("5. I work overnights");
            Console.WriteLine("6. my favorite color is black");
            Console.WriteLine("7. I ride a motorcycle");
            Console.WriteLine("8. I have 3 speeding tickets");
            Console.WriteLine("9. I have 4 dogs");
            Console.WriteLine("10. I have 2 cats");
            Console.Write("Press Enter for the next 11-20 things about me");
            Console.ReadLine();
            Console.WriteLine("11. I'm studying to be a Mechanical Engineer");
            Console.WriteLine("12. I'm planning to transfer to Fresno State");
            Console.WriteLine("13. I got adult responsibilities like paying all the house bills");
            Console.WriteLine("14. I've been working since high school");
            Console.WriteLine("15. I like learning new skills");
            Console.WriteLine("16. I'm motivated by my family");
            Console.WriteLine("17. My girlfriend inspired me to come back to school");
            Console.WriteLine("18. I love pizza");
            Console.WriteLine("19. Horchata is my favorite type of water to drink");
            Console.WriteLine("20. My anniversary with my girlfriend just pass and we're 5 years strong");
            Console.Write("Press Enter for the next 21-30 things about me");
            Console.ReadLine();
            Console.WriteLine("21. I like trying new foods");
            Console.WriteLine("22. I am not a picky eater");
            Console.WriteLine("23. I'm starting to like hot coffee");
            Console.WriteLine("24. I like playing video games");
            Console.WriteLine("25. I'm the youngest of my family");
            Console.WriteLine("26. I listen to classical music while doing my homework.");
            Console.WriteLine("27. My favorite character in Star Wars in Anakin/Darth Vader");
            Console.WriteLine("28. I'm a Star Wars fan");
            Console.WriteLine("29. I'm the youngest of my family");
            Console.WriteLine("30. I gave up smoking weed and I'm sad");
            Console.Write("Press Enter for the next 31-40 things about me");
            Console.ReadLine();
            Console.WriteLine("31. I'm a homebody");
            Console.WriteLine("32. I like going to disneyland");
            Console.WriteLine("33. I try my best to stay positive");
            Console.WriteLine("34. I like making people laugh");
            Console.WriteLine("35. I really appreciate the small moments in life");
            Console.WriteLine("36. I'm grateful for the people in my life");
            Console.WriteLine("37. I'm currectly watching rom-com movies");
            Console.WriteLine("38. I think of myself as a food critique");
            Console.WriteLine("39. I also think of myself as a movie critique");
            Console.WriteLine("40. My favorite genre of video games are RPG fantasy ");
            Console.Write("Press Enter for the next 41-50 things about me");
            Console.ReadLine();
            Console.WriteLine("41. I have a twin");
            Console.WriteLine("42. I like wearing crocs");
            Console.WriteLine("43. I only have one pair of pants");
            Console.WriteLine("44. I don't have any jeans");
            Console.WriteLine("45. I love to wear baggy clothes");
            Console.WriteLine("46. I'm excellent driver");
            Console.WriteLine("47. I have a niece and a nephew");
            Console.WriteLine("48. I don't have any human kids of my own");
            Console.WriteLine("49. I'm 25 years old");
            Console.WriteLine("50. I like conspiracy theories");
            Console.Write("Press Enter for the next 51-60 things about me");
            Console.ReadLine();
            Console.WriteLine("51. I like hot weather more than the cold");
            Console.WriteLine("52. I like watching sunsets");
            Console.WriteLine("53. In highschool I played sports");
            Console.WriteLine("54. I don't like planning things, I just got with the flow");
            Console.WriteLine("55. I like watching anime");
            Console.WriteLine("56. I enjoy quiet mornings");
            Console.WriteLine("57. I sometimes like sleeping in");
            Console.WriteLine("58. I want to keep growing academically");
            Console.WriteLine("59. I want to start being healthier");
            Console.WriteLine("60. My favorite disneyland food is actually in California Adventure Park and it's the quesabirrias");
            Console.Write("Press enter for the next 61-70 things about me");
            Console.ReadLine();
            Console.WriteLine("61. I'm learning to have patience");
            Console.WriteLine("62. I like being productive");
            Console.WriteLine("63. I like to go to the casino");
            Console.WriteLine("64. I really like playing blackjack");
            Console.WriteLine("65. I love to bowl");
            Console.WriteLine("66. I hate country music");
            Console.WriteLine("67. I like spending time with my girlfriend");
            Console.WriteLine("68. I stay calm when things get chaotic");
            Console.WriteLine("69. I think more logically than emotionally ");
            Console.WriteLine("70. I like driving fast");
            Console.Write("Press Enter for the next 71-80 things about me");
            Console.ReadLine();
            Console.WriteLine("71. I was bulking");
            Console.WriteLine("72. I enjoy late night snacks ");
            Console.WriteLine("73. I like sunny days");
            Console.WriteLine("74. I like learning random facts");
            Console.WriteLine("75. I like listening to music while i work");
            Console.WriteLine("76. I sleep all day on my days off");
            Console.WriteLine("77. I like learning how things work mechanically");
            Console.WriteLine("78. I just got a new dog");
            Console.WriteLine("79. I like keeping my space organized");
            Console.WriteLine("80. I like helping people when they need advice");
            Console.Write("Press Enter for the next 81-90 things about me");
            Console.ReadLine();
            Console.WriteLine("81. I like being around people who motivated me");
            Console.WriteLine("82. I enjoy watching documentaries");
            Console.WriteLine("83. I like setting goals for myself");
            Console.WriteLine("84. I like watching funny videos to relax");
            Console.WriteLine("85. I enjoy simple routines that keep me grounded");
            Console.WriteLine("86. I used to be really good at drawing");
            Console.WriteLine("87. I like harry potter");
            Console.WriteLine("88. I am a ravenclaw");
            Console.WriteLine("89. I enjoy trying new restaurants");
            Console.WriteLine("90. I just wear baggy and comfortable clothes");
            Console.Write("Press Enter for the next 91-100 things about me");
            Console.ReadLine();
            Console.WriteLine("91. I like working 12 hour shifts when I dont have school");
            Console.WriteLine("92. I dislike people who drink and drive");
            Console.WriteLine("93. Everyday I strive to become a better version of myself");
            Console.WriteLine("94. I like carrot cake");
            Console.WriteLine("95. I know how to dance");
            Console.WriteLine("96. I don't really drink alcohol");
            Console.WriteLine("97. I know how to cook");
            Console.WriteLine("98. I know how to bake");
            Console.WriteLine("99. I learned to drive thanks to video games");
            Console.WriteLine("100. I've been playing video games since I was 4 years old");
            

        }
    }
}
